services:
  - type: web
    name: uznr-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && (python manage.py import_seed &) && gunicorn config.wsgi --log-file -"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://uznr.netlify.app"
      - key: PYTHON_VERSION
        value: "3.13.0"
