# Generated by Django 6.1 on 2026-08-13 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name'], 'verbose_name': 'Član', 'verbose_name_plural': 'Članovi'},
        ),
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-date'], 'verbose_name': 'Vijest', 'verbose_name_plural': 'Vijesti'},
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.newsitem')),
            ],
            options={
                'verbose_name': 'Fotografija',
                'verbose_name_plural': 'Fotografije',
                'ordering': ['order', 'id'],
            },
        ),
    ]
