# Generated by Django 6.1 on 2026-08-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_member_options_alter_newsitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='member',
            name='url',
            field=models.URLField(verbose_name='Veb adresa'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='news_gallery/', verbose_name='Fotografija'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Manji broj = prikazuje se prije.', verbose_name='Redoslijed'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=models.TextField(blank=True, help_text='Puni tekst koji se prikazuje na stranici vijesti.', null=True, verbose_name='Tekst vijesti'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='date',
            field=models.DateField(verbose_name='Datum objave'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='excerpt',
            field=models.TextField(help_text='Prikazuje se na početnoj stranici i u arhivi, ispod naslova.', verbose_name='Kratak opis'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='slug',
            field=models.SlugField(help_text='Automatski se popunjava iz naslova. Koristi se u adresi stranice.', unique=True, verbose_name='Link (slug)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Glavna slika koja se prikazuje uz vijest.', null=True, upload_to='news/', verbose_name='Naslovna fotografija'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Naslov'),
        ),
    ]
