# Generated by Django 6.1 on 2026-08-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_member_logo_alter_member_name_alter_member_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Naziv')),
                ('url', models.URLField(blank=True, help_text='Za link ka spoljnoj stranici (npr. sajt ministarstva).', verbose_name='Veb adresa')),
                ('file', models.FileField(blank=True, help_text='Za dokument koji se otprema i čuva na našem sajtu (PDF i sl.). Popuni ili ovo, ili adresu iznad — ne oboje.', upload_to='important_links/', verbose_name='Fajl')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manji broj = prikazuje se prije.', verbose_name='Redoslijed')),
            ],
            options={
                'verbose_name': 'Važan link',
                'verbose_name_plural': 'Važni linkovi',
                'ordering': ['order', 'id'],
            },
        ),
    ]
