# Generated by Django 6.1 on 2026-08-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_importantlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantlink',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo institucije koji se prikazuje uz link.', null=True, upload_to='important_links_logos/', verbose_name='Logo'),
        ),
    ]
