# Generated by Django 6.1 on 2026-08-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_importantlink_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Naslov')),
                ('excerpt', models.TextField(verbose_name='Tekst oglasa')),
                ('date', models.DateField(verbose_name='Datum objave')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='oglasi/', verbose_name='Fotografija')),
                ('link', models.URLField(blank=True, help_text='Opciono — npr. link za prijavu ili više informacija.', verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Oglas',
                'verbose_name_plural': 'Oglasi',
                'ordering': ['-date'],
            },
        ),
    ]
