# Generated by Django 6.1 on 2026-08-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': [models.OrderBy(models.F('date'), descending=True, nulls_last=True), '-id'], 'verbose_name': 'Oglas', 'verbose_name_plural': 'Oglasi'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='link_label',
            field=models.CharField(blank=True, help_text='Npr. "Prijava putem portala eUprava". Ostavi prazno za podrazumijevani tekst.', max_length=100, verbose_name='Tekst linka'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(blank=True, help_text='Ostavi prazno ako datum nije poznat — oglas će se prikazati bez datuma.', null=True, verbose_name='Datum objave'),
        ),
    ]
