# Generated by Django 6.1 on 2026-08-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_announcement_options_announcement_link_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_open', models.OrderBy(models.F('date'), descending=True, nulls_last=True), '-id'], 'verbose_name': 'Oglas', 'verbose_name_plural': 'Oglasi'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Isključi kada rok istekne ili se pozicija popuni — oglas ostaje na sajtu, ali se označava kao "Isteklo".', verbose_name='Aktivan (otvoren)'),
        ),
    ]
