# Generated by Django 6.1 on 2026-08-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_announcement_options_announcement_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Naziv')),
                ('url', models.URLField(blank=True, help_text='Za link ka spoljnoj stranici.', verbose_name='Veb adresa')),
                ('file', models.FileField(blank=True, help_text='Za dokument koji se otprema i čuva na našem sajtu (PDF i sl.). Popuni ili ovo, ili adresu iznad — ne oboje.', upload_to='oglasi_dokumenti/', verbose_name='Fajl')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manji broj = prikazuje se prije.', verbose_name='Redoslijed')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.announcement')),
            ],
            options={
                'verbose_name': 'Dokument uz oglas',
                'verbose_name_plural': 'Dokumenti uz oglas',
                'ordering': ['order', 'id'],
            },
        ),
    ]
