# Generated by Django 6.1 on 2026-08-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_announcementlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Oglas', 'verbose_name_plural': 'Oglasi'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Manji broj = prikazuje se prije. Prvi oglas (najmanji broj) se prikazuje istaknuto, u većoj kartici.', verbose_name='Redoslijed'),
        ),
    ]
