# Generated by Django 6.1 on 2026-08-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_announcement_options_announcement_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ime i prezime')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('organisation', models.CharField(blank=True, max_length=200, verbose_name='Organizacija')),
                ('subject', models.CharField(choices=[('general', 'Opšte pitanje'), ('membership', 'Članstvo u Udruženju'), ('exam', 'Stručni ispit i obuke'), ('cooperation', 'Saradnja i projekti'), ('media', 'Mediji i najave')], default='general', max_length=20, verbose_name='Tema')),
                ('message', models.TextField(verbose_name='Poruka')),
                ('language', models.CharField(default='mne', help_text='Jezik sajta na kojem je poruka poslata — potvrda se šalje na tom jeziku.', max_length=5, verbose_name='Jezik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Primljeno')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('in_progress', 'U obradi'), ('answered', 'Odgovoreno')], default='new', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Vidljivo samo u administraciji.', verbose_name='Interna bilješka')),
                ('confirmation_sent_at', models.DateTimeField(blank=True, help_text='Vrijeme slanja automatske potvrde pošiljaocu. Prazno znači da slanje nije uspjelo.', null=True, verbose_name='Potvrda poslata')),
            ],
            options={
                'verbose_name': 'Poruka sa sajta',
                'verbose_name_plural': 'Poruke sa sajta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Mora odgovarati adresi na sajtu, npr. "regulativa" za /regulativa.', unique=True, verbose_name='Adresa stranice (slug)')),
                ('title', models.CharField(max_length=200, verbose_name='Naslov')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Naslov (EN)')),
                ('intro', models.TextField(blank=True, verbose_name='Uvodni tekst')),
                ('intro_en', models.TextField(blank=True, verbose_name='Uvodni tekst (EN)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Izmijenjeno')),
            ],
            options={
                'verbose_name': 'Stranica',
                'verbose_name_plural': 'Stranice',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Tekst'), ('links', 'Linkovi'), ('documents', 'Dokumenti'), ('images', 'Galerija fotografija'), ('faq', 'Pitanja i odgovori')], default='text', help_text='Određuje kako se sekcija prikazuje na sajtu. "Tekst" koristi samo polja ispod; ostali tipovi koriste i stavke.', max_length=20, verbose_name='Tip sekcije')),
                ('heading', models.CharField(blank=True, max_length=200, verbose_name='Naslov sekcije')),
                ('heading_en', models.CharField(blank=True, max_length=200, verbose_name='Naslov sekcije (EN)')),
                ('body', models.TextField(blank=True, help_text='Prazan red razdvaja pasuse.', verbose_name='Tekst')),
                ('body_en', models.TextField(blank=True, verbose_name='Tekst (EN)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manji broj = prikazuje se prije.', verbose_name='Redoslijed')),
                ('is_visible', models.BooleanField(default=True, help_text='Isključi da sekcija privremeno nestane sa sajta bez brisanja.', verbose_name='Prikazano')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page', verbose_name='Stranica')),
            ],
            options={
                'verbose_name': 'Sekcija',
                'verbose_name_plural': 'Sekcije',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Naziv')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Naziv (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('description_en', models.TextField(blank=True, verbose_name='Opis (EN)')),
                ('url', models.URLField(blank=True, help_text='Za link ka spoljnoj stranici.', verbose_name='Veb adresa')),
                ('file', models.FileField(blank=True, help_text='Za dokument koji se čuva na našem sajtu (PDF i sl.). Popuni ili ovo, ili adresu iznad — ne oboje.', upload_to='stranice/dokumenti/', verbose_name='Fajl')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stranice/slike/', verbose_name='Fotografija')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manji broj = prikazuje se prije.', verbose_name='Redoslijed')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.pagesection', verbose_name='Sekcija')),
            ],
            options={
                'verbose_name': 'Stavka',
                'verbose_name_plural': 'Stavke',
                'ordering': ['order', 'id'],
            },
        ),
    ]
