# Generated by Django 6.1 on 2026-08-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_contactmessage_page_pagesection_sectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='date_label',
            field=models.CharField(blank=True, help_text='Prikazuje se kako je unijet, npr. 20.03.2026.', max_length=60, verbose_name='Datum (tekst)'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='image_url',
            field=models.CharField(blank=True, help_text='Koristi se samo kada fotografija već postoji na sajtu (npr. /press/slika.jpg). Ako otpremite fotografiju iznad, ona ima prednost.', max_length=500, verbose_name='Adresa fotografije'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Broj strana'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='reference',
            field=models.CharField(blank=True, help_text='Npr. „Službeni list Crne Gore“, br. 051/26 — ili naziv medija za press objave.', max_length=300, verbose_name='Izvor / broj službenog lista'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='reference_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Izvor (EN)'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='size_kb',
            field=models.PositiveIntegerField(blank=True, help_text='Popunjava se automatski pri otpremanju fajla.', null=True, verbose_name='Veličina (KB)'),
        ),
    ]
