# Generated by Django 6.1 on 2026-08-16 14:09

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_sectionitem_date_label_sectionitem_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='url',
            field=models.CharField(blank=True, help_text='Puna adresa (https://…) za spoljnu stranicu, ili putanja do dokumenta koji je već na sajtu (npr. /documents/regulativa/zakon.pdf).', max_length=500, validators=[content.models.validate_link], verbose_name='Veb adresa'),
        ),
    ]
