# Generated by Django 6.1 on 2026-08-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_sectionitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Naslov'),
        ),
    ]
