# Generated by Django 6.1 on 2026-08-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_contactmessage_organisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'sekcija',
                'verbose_name_plural': 'sekcije',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagesection',),
        ),
        migrations.CreateModel(
            name='SinglePageContent',
            fields=[
            ],
            options={
                'verbose_name': 'stavka',
                'verbose_name_plural': 'stavke',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sectionitem',),
        ),
        migrations.AddField(
            model_name='announcement',
            name='excerpt_en',
            field=models.TextField(blank=True, verbose_name='Tekst oglasa (EN)'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='link_label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tekst linka (EN)'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Naslov (EN)'),
        ),
        migrations.AddField(
            model_name='announcementlink',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Naziv (EN)'),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Naziv (EN)'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Tekst vijesti (EN)'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='excerpt_en',
            field=models.TextField(blank=True, verbose_name='Kratak opis (EN)'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Naslov (EN)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Postavlja se prevlačenjem reda u tabeli. Prvi oglas se prikazuje istaknuto, u većoj kartici.', verbose_name='Redoslijed'),
        ),
        migrations.AlterField(
            model_name='announcementlink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Postavlja se prevlačenjem reda u tabeli.', verbose_name='Redoslijed'),
        ),
        migrations.AlterField(
            model_name='importantlink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Postavlja se prevlačenjem reda u tabeli.', verbose_name='Redoslijed'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Postavlja se prevlačenjem reda u tabeli.', verbose_name='Redoslijed'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Postavlja se prevlačenjem reda u tabeli.', verbose_name='Redoslijed'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Postavlja se prevlačenjem reda u tabeli.', verbose_name='Redoslijed'),
        ),
        migrations.CreateModel(
            name='BibliotekaPage',
            fields=[
            ],
            options={
                'verbose_name': 'grupa u Biblioteci',
                'verbose_name_plural': 'Biblioteka',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontentproxy',),
        ),
        migrations.CreateModel(
            name='ProjektiPage',
            fields=[
            ],
            options={
                'verbose_name': 'projekat',
                'verbose_name_plural': 'Projekti',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontentproxy',),
        ),
        migrations.CreateModel(
            name='RegulativaPage',
            fields=[
            ],
            options={
                'verbose_name': 'grupa na stranici Regulativa',
                'verbose_name_plural': 'Regulativa',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontentproxy',),
        ),
        migrations.CreateModel(
            name='PitanjaPage',
            fields=[
            ],
            options={
                'verbose_name': 'pitanje',
                'verbose_name_plural': 'Pitanja i odgovori',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.singlepagecontent',),
        ),
        migrations.CreateModel(
            name='PressPage',
            fields=[
            ],
            options={
                'verbose_name': 'objava u medijima',
                'verbose_name_plural': 'Press / Mediji',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.singlepagecontent',),
        ),
        migrations.CreateModel(
            name='PublikacijePage',
            fields=[
            ],
            options={
                'verbose_name': 'publikacija',
                'verbose_name_plural': 'Publikacije',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.singlepagecontent',),
        ),
    ]
